groups:
  - name: alert.example
    rules:
      - alert: HighCPUUsage
        expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High CPU Usage
          description: "CPU usage is above 90% on instance {{ $labels.instance }}"

      - alert: HighMemoryUsage
        expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100 < 10
        for: 10m
        labels:
          severity: critical
        annotations:
          summary: High Memory Usage
          description: "Memory usage is above 90% on instance {{ $labels.instance }}"

  - name: alert.rules
    rules:
    - alert: InstanceDown
      expr: up == 0
      for: 1m
      labels:
        severity: "critical"
      annotations:
        summary: "Endpoint {{ $labels.instance }} down"
        description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minutes."
    
    - alert: HostOutOfMemory
      expr: node_memory_MemAvailable / node_memory_MemTotal * 100 < 25
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Host out of memory (instance {{ $labels.instance }})"
        description: "Node memory is filling up (< 25% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"


    - alert: HostOutOfDiskSpace
      expr: (node_filesystem_avail{mountpoint="/"}  * 100) / node_filesystem_size{mountpoint="/"} < 50
      for: 1s
      labels:
        severity: warning
      annotations:
        summary: "Host out of disk space (instance {{ $labels.instance }})"
        description: "Disk is almost full (< 50% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"


    - alert: HostHighCpuLoad
      expr: (sum by (instance) (irate(node_cpu{job="node_exporter_metrics",mode="idle"}[5m]))) > 80
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Host high CPU load (instance {{ $labels.instance }})"
        description: "CPU load is > 80%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

  - name: new.alert.rules
    rules:
    - alert: InstanceDown
    # Condition for alerting
      expr: up == 0
      for: 1m
    # Annotation - additional informational labels to store more information
      annotations:
        title: 'Instance {{ $labels.instance }} down'
        description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute.'
    # Labels - additional labels to be attached to the alert
      labels:
          severity: 'critical'

    - alert: HostOutOfMemory
    # Condition for alerting
      expr: node_memory_MemAvailable / node_memory_MemTotal * 100 < 25
      for: 5m
    # Annotation - additional informational labels to store more information
      annotations:
        title: 'Host out of memory (instance {{ $labels.instance }})'
        description: 'Node memory is filling up (< 25% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}'
    # Labels - additional labels to be attached to the alert
      labels:
          severity: 'warning'

    - alert: HostHighCpuLoad
    # Condition for alerting
      expr: (sum by (instance) (irate(node_cpu{job="node_exporter_metrics",mode="idle"}[5m]))) > 80
      for: 5m
    # Annotation - additional informational labels to store more information
      annotations:
        title: 'Host high CPU load (instance {{ $labels.instance }})'
        description: 'CPU load is > 80%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}'
    # Labels - additional labels to be attached to the alert
      labels:
          severity: 'warning'

    - alert: HostOutOfDiskSpace
    # Condition for alerting
      expr: (node_filesystem_avail{mountpoint="/"}  * 100) / node_filesystem_size{mountpoint="/"} < 50
      for: 5m
    # Annotation - additional informational labels to store more information
      annotations:
        title: 'Host out of disk space (instance {{ $labels.instance }})'
        description: 'Disk is almost full (< 50% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}'
    # Labels - additional labels to be attached to the alert
      labels:
          severity: 'warning'