---
- name: Set timezone
  community.general.timezone:
    name: "{{timezone}}"
  tags:
    - agent
    - monitor
- name: Install required packages
  import_tasks: install_requirements.yml
  become: True
  tags:
    - agent
    - monitor
- name: Create a docker network
  docker_network:
    name: "{{item}}"
  loop:
    - monitoring
  tags:
    - monitor
- name: Create a docker network
  docker_network:
    name: "{{item}}"
  loop:
    - monitoring
    - db
  tags:
    - db
- name: Create a docker network
  docker_network:
    name: "{{item}}"
  loop:
    - monitoring
    - app
  tags:
    - app
- name: Setup server for sending mails
  import_tasks: setup_ssmtp_server.yml
  tags:
    - monitor
- name: Install_containers
  import_tasks: install_containers.yml
  tags:
    - monitor
- name: Install alertmanager
  import_tasks: install_alertmanager.yml
  tags:
    - monitor
# Install monitoring agents
- name: Install monitoring agents
  import_tasks: install_agents.yml
  tags:
    - agent
    - monitor


