---
all:
  children:
    servers:
      children:
        local:
          children:
            ubuntu:
              children:
                application:
                  hosts:
                    app-server:
                      ansible_host: 54.144.244.50
                database:
                  hosts:
                    db-server:
                      ansible_host: 18.234.88.130
                # bastion:
                #   hosts:
                #     bastion-server:
                #       ansible_host: 3.90.11.111
                monitoring:
                  hosts:
                    monitoring-server:
                      ansible_host: 44.211.170.58
 